### PR TITLE
Implementing monthly pattern inputs

### PR DESCRIPTION
**Pull request by Bachibouzouk**
This PR adds options for command line ramp to generate range based on actual dates and having the day_type (week or weekend) automatically sorted.

Previously the first generated day was always a Monday.

The changes are documented directly in the documentation under 

`/examples/year_simulation/year_simulation.html#date-range-input-section`

and 

`intro.html#spreadsheet-input-files` 

As mentionned earlier I don't have enough rights to setup automatic RTD builds for PRs, I documented the procedure in https://github.com/open-plan-tool/documentation/pull/98#issue-1536210374

I could build the docs from our fork and it is here : https://ramp-rli.readthedocs.io/en/feature-yearly-pattern/

### CODE REVIEW

**Comment by Bachibouzouk** [comment]
In this PR I remove the variable `Year_behavior`, but now I notice it was quite heavily used in the examples. I think we should discuss about its usage as back-compatibility, or that we keep it as is or we get rid of it altogether. What I noticed is that the argument `prof_i` for the ith profile is always provided as an int and though that we could simply feed a `day_type` argument to the function by `day_type=yearly_pattern[prof_i]`

**Comment by Bachibouzouk** [comment]
This is partly to address #35 that I modified this

**Comment by Bachibouzouk** [comment]
I think there are also 2 types of RAMP users at least, the ones who write python files to run ramp models and the ones using spreadsheets as inputs, running ramp from the command line (most likely people with no or little knowledge of python). We should aim the docs to please at least those 2 types of users. What do you think @FLomb , @mohammadamint ?

**Comment by mohammadamint** [comment]
> 

I strongly agree with removing the variable, and I will take care of modifying the examples without any issues.

**Comment by mohammadamint** [comment]
> In this PR I remove the variable `Year_behavior`, but now I notice it was quite heavily used in the examples. I think we should discuss about its usage as back-compatibility, or that we keep it as is or we get rid of it altogether. What I noticed is that the argument `prof_i` for the ith profile is always provided as an int and though that we could simply feed a `day_type` argument to the function by `day_type=yearly_pattern[prof_i]`

@Bachibouzouk I strongly agree with removing the variable and if we do so, I will modify the documents accordingly without any issues.

**Comment by mohammadamint** [comment]
>

**Comment by mohammadamint** [comment]
> I think there are also 2 types of RAMP users at least, the ones who write python files to run ramp models and the ones using spreadsheets as inputs, running ramp from the command line (most likely people with no or little knowledge of python). We should aim the docs to please at least those 2 types of users. What do you think @FLomb , @mohammadamint ?

Agree. I still consider the documentation a work in progress. Probably we need to identify the essential improvements needed in the next group meeting with clearer tasks on documentation.

**Comment by Bachibouzouk** [comment]
> @Bachibouzouk I strongly agree with removing the variable and if we do so, I will modify the documents accordingly without any issues.

I had already modified them, it wasn't so long :) I will push those changes now

**Comment by Bachibouzouk** [comment]
@mohammadamint, @FLomb - I reworked the PR to clean and regroup the commits so that they are easier to review for you :)

**Review by mohammadamint — COMMENTED** [review]
Is it possible to add an example on how to use the functionality when using a python script to build/run a model?

**Review by mohammadamint — COMMENTED** [review]
I was wondering if the same feature can be implemented in ramp core so it can be used when a model is built using python script or not.

**Comment by Bachibouzouk** [comment]
> I was wondering if the same feature can be implemented in ramp core so it can be used when a model is built using python script or not.

Day type input is implemented in ramp core

**Comment by Bachibouzouk** [comment]
> I was wondering if the same feature can be implemented in ramp core so it can be used when a model is built using python script or not.

you mean something like 
`ramp -i <path to a python script> --start-date YYYY-MM-DD` 

?

**Comment by mohammadamint** [comment]
> > I was wondering if the same feature can be implemented in ramp core so it can be used when a model is built using python script or not.
> 
> you mean something like `ramp -i <path to a python script> --start-date YYYY-MM-DD`
> 
> ?

I meant more like a method or function that helps the user to do the same when building and running a model in a python IDE (like the Jupyter Notebook examples in the documentation).

**Review by mohammadamint — COMMENTED** [review]
Just noticed that this function is missed in the docs. Probably it deserves an example with some explanation. I can take care of it!

**Comment by Bachibouzouk** [comment]
> Just noticed that this function is missed in the docs. Probably it deserves an example with some explanation. I can take care of it!

is it? I though I added a section about it in this very PR, see the first post for link to the updated docs online

**Comment by Bachibouzouk** [comment]
> I meant more like a method or function that helps the user to do the same when building and running a model in a python IDE (like the Jupyter Notebook examples in the documentation).

I see, yes this is possible to pack this in a function and use this function in `cli.py` as well. That way this feature is available to python devs as well as spreadsheet users

**Comment by Bachibouzouk** [comment]
@mohammadamint - I started to look how I could make the date input usable directly in the python code and I noticed to make this change it would require more time. I suggest that I tackle that in a subsequent PR, because #54 cannot be merged prior to this PR and I would like to close some PRs, I will open an issue as assign it to me

**Comment by mohammadamint** [comment]
> @mohammadamint - I started to look how I could make the date input usable directly in the python code and I noticed to make this change it would require more time. I suggest that I tackle that in a subsequent PR, because #54 cannot be merged prior to this PR and I would like to close some PRs, I will open an issue as assign it to me

@Bachibouzouk Absolutely makes sense.

**Comment by Bachibouzouk** [comment]
@mohammadamint @FLomb  - now the docs built automatically, as I will tackle the suggested changes in a subsequent PR, can this one be approved?

**Comment by Bachibouzouk** [comment]
@mohammadamint , @FLomb ?

**Comment by mohammadamint** [comment]
> @mohammadamint , @FLomb ?

I would proceed with merging and closing this PR.

**Review by mohammadamint — COMMENTED** [review]
I would proceed with merging and closing this PR.

**Comment by Bachibouzouk** [comment]
@mohammadamint - I will merge then, I think I was awaiting a "approved" ticked :) but now I can bypass them

**Pull request merged**
