### PR TITLE
Release v0.5.2

### PR DESCRIPTION
**Pull request by Bachibouzouk**
- [x] The changelog should be filled here
- [x] The version number should be bumped
- [x] Test release should be performed with release candidates

### CODE REVIEW

**Comment by FLomb** [comment]
Hi,

Some issues I detected:

- The conversion of .py files into .xlsx files is not working again. The code looks for modules instead of files, even though we had already fixed this bug before. Apparently, it was reintroduced at some point through other means because the lines that caused the error in the past are not there anymore. 
- The qualitative testing functionality is not working due to some broken paths in what `test_run.py` tries to do.
- In the docs, in 'RAMP introduction/contributing', we provide a link to the 'Contribution guidelines'. However, the link is broken - not sure if this is the case only because I am looking at the docs generated within the PR.

**Comment by Bachibouzouk** [comment]
> * The qualitative testing functionality is not working due to some broken paths in what `test_run.py` tries to do.

Test_run is only supposed to be runnable if you are developping and installed ramp locally with `pip install -e .`

**Comment by Bachibouzouk** [comment]
> * In the docs, in 'RAMP introduction/contributing', we provide a link to the 'Contribution guidelines'. However, the link is broken - not sure if this is the case only because I am looking at the docs generated within the PR.

This one at least works locally, it is most certainly a problem of file path, or maybe we need to push the copy of the Contribute.md file as well (locally the file is copied and included in the index directly as wagtail allows a mix and match of .rst and .md files)

**Review by FLomb — APPROVED** [review]
I've tested the PR, and it works smoothly; thanks for the work, @Bachibouzouk

**Pull request merged**
