### PR TITLE
switch on + App.func_cycle < rand_window_123[1]

### PR DESCRIPTION
**Pull request by PasquinoFI**
If the inequality in the title is not respected, the app does not have time to finish its cycle before the end of the window. This is especially a problem when modeling complex cycles such as that of an oven or a dishwasher or washing machine. Without the control, the cycle was broken and ended unrealistically at the beginning of the window.
This bag has been easly fixed and now the simulations should be more realistic.

first image is the right cycle, with the old code the second cycle could sometimes happens

correct_oven
uncorrect_oven

### CODE REVIEW

**Comment by FLomb** [comment]
Hi @PasquinoFI,

Thanks for your PR. Would you please have a look at the ('How to contribute')[https://github.com/RAMP-project/RAMP/blob/master/CONTRIBUTING.md] section and try to run the minimal test for this PR?

**Comment by PasquinoFI** [comment]
Hi @FLomb thank you for your reply.
I have already followed all the procedures indicated in "Hot to contribute" before opening the pull request.

**Comment by PasquinoFI** [comment]
Hi guys.

Answer to FLomb:
1) there is a way to handle this but it involves breaking the loop and creating a new shorter one to achieve the time the app needs to be on during the day , as shown in the second figure.
2) I had originally tried what you are proposing but then some simulations would go into a loop. Not understanding why, I opted for another option.

Answer to Bachibozouk:
okey no problem. So, should I do something to fix it or can you do it? Sorry I am still not very familiar with github.

**Comment by PasquinoFI** [comment]
Hi guys

answer to FLomb:
1) Currently the situation is solved by breaking the cycle and creating a new shorter one to reach the time the app needs to be on during the day. As can be seen from the second image.
2) I initially tried what you propose but some of the simulations would loop. Not understanding why, I opted for another option.

Answer to Bachibouzouk;
Okey. Could you kindly explain how I should edit the pull request without these commits? I am still not very familiar with github.

Thanks

**Comment by Bachibouzouk** [comment]
@PasquinoFI - one thing you could do is rebase your branch on `master` and choose to stop and edit the commits (`git rebase -i master` to do so and follow the instructions in the terminal (you can stop the process at any time by typing `git rebase --abort`))

Alternatively you can do `git reset --soft <no of commit before your first commit on this branch>` or `git reset --soft master`, this will destroy the commits but keep the changes, then you can recommit only the relevant files (you can reuse the commit messages from here). Then you have to force push the new commits with `git push origin fix_func_cycle:fix_func_cycle -f`  (because the history of your local and remote branch would have diverged due to the `git reset`)

Maybe start by making a local copy of `fix_func_cycle` (`git checkout fix_func_cycle` and `git checkout -b backup/fix_func_cycle`, then `git checkout fix_func_cycle` before starting rebasing or resetting)

**Comment by PasquinoFI** [comment]
Done it. 
I should have commit only stochastic_process.py
Let me know if it's okay

**Comment by Bachibouzouk** [comment]
> Done it. I should have commit only stochastic_process.py Let me know if it's okay

Unfortunately if you look above in "File changed" you still see 21 files. I think what you did is commit the new commit [67ae862](https://github.com/RAMP-project/RAMP/pull/28/commits/67ae8621c0650692d09e3ce26debcee2d48e422b) on top of the old ones

**Comment by PasquinoFI** [comment]
Sorry.

Now it should be okay, isn't it?

Thanks for helping and patience

**Comment by Bachibouzouk** [comment]
> Now it should be okay, isn't it?

Yes it looks good :) !

Unfortunately I don't have rights on this repository so you'll have to wait for approval by @FLomb :)

**Comment by FLomb** [comment]
Thanks for the work here guys, I've read the reply to my questions by @PasquinoFI and they seem sensible. Before merging, I want to take a few minutes to look back at the code and see if indeed it works best with the proposed solution. I'll do so asap

**Comment by Bachibouzouk** [comment]
@FLomb actually merging @PasquinoFI PR now would make a lot of work rebasing the refactored code
I would propose to include the change in the refactoring PR
as it is only a few lines
what do you think?

**Comment by FLomb** [comment]
The changes in this PR are included in PR #54. This PR can be then closed.

**Pull request closed without merging**
