### PR TITLE
Small fixes before the release

### PR DESCRIPTION
**Pull request by Bachibouzouk**
- [x] fix the conversion from .py to .xlsx
- [x] fix the link to contribution.html
- [x] fix test_run.py
- [x] fix unexpected warning on appliances with duty cycles

### CODE REVIEW

**Comment by Bachibouzouk** [comment]
Contributing.html is browsable locally with the docs but somehow not online, I need to have a closer look at it, somehow commiting the .md file did not solve the issue

**Comment by FLomb** [comment]
Hi,

I've pushed a commit that fixes the path issues in `test_run.py`, as long as the file is run from the root folder, as indicated in our contributing guidelines. So that's done. I've also introduced a `random_seed=True` parameter, which may be matched with reference outputs also generated via random seed in future upgrades of the code.

Nonetheless, in implementing such a fix, I bumped into other small issues. Namely, I get the following warning for all three input files:
`The app  has duty cycle option on, however the switch on event fell outside the provided duty cycle windows`

The warning poses 2 issues: 
1. The warning string does not work as expected, because it's supposed to provide the appliance name (in the code, the string is: ` f"The app {self.name} has duty cycle...`) and it does not do so;
2. The warning should not be there in the first place, I suppose. So this warning is either triggered unnecessarily, or something is wrong in the input files (which I doubt).

**Comment by Bachibouzouk** [comment]
> 1. The warning string does not work as expected, because it's supposed to provide the appliance name (in the code, the string is: ` f"The app {self.name} has duty cycle...`) and it does not do so;

The app name seem to be ""

**Comment by Bachibouzouk** [comment]
> 2\. The warning should not be there in the first place, I suppose. So this warning is either triggered unnecessarily, or something is wrong in the input files (which I doubt).

I found the following comment in the code 
``` 
                    # TODO previously duty_cycle3 was always considered as default if the evaluate proxy did neither
                    #  get selected by duty_cycle1 nor duty_cycle2, for default is kept but not silently anymore in
                    #  order to see whether this is an issue or not
``

**Comment by Bachibouzouk** [comment]
> 2\. The warning should not be there in the first place, I suppose. So this warning is either triggered unnecessarily, or something is wrong in the input files (which I doubt).

@FLomb - the warning was actually showing some odd behavior which was swept under the rug before, see #153 (it does not modify tremenduously the example profiles, fortunately :))

**Review by FLomb — APPROVED** [review]
I tested extensively the PR locally, and all seems to work very smoothly. I am happy to approve it. Thanks, @Bachibouzouk !

**Pull request merged**
