### PR TITLE
solving the test.pypi release issue #96

### LINKED ISSUE #96: solving the test.pypi release issue
To make the test.pypi Action work, the first release should be done manually, to get the API Token.

The API Token needs to be updated accordingly.

### PR DESCRIPTION
**Pull request by mohammadamint**
Closes #96 

updating the secrets for API Token for the automatic test release of software after Pushes and PRs to developemnt and main

### CODE REVIEW

**Comment by mohammadamint** [comment]
@FLomb the action is failing due to some syntax error in README.rst:

ERROR    `long_description` has syntax errors in markup and would not be        
         rendered on PyPI.                                                      
         line 65: Warning: Title underline too short.     

Is this solved in your new PR?

**Comment by FLomb** [comment]
> @FLomb the action is failing due to some syntax error in README.rst:
> 
> ERROR `long_description` has syntax errors in markup and would not be rendered on PyPI. line 65: Warning: Title underline too short.
> 
> Is this solved in your new PR?

Hi, I have updated PR #95  to fix the mismatch between the title length and the underlying "~" string. Is that the issue here? However, I haven't yet merged PR #95 due to some other failing tests.

**Comment by FLomb** [comment]
> > > @FLomb the action is failing due to some syntax error in README.rst:
> > > ERROR `long_description` has syntax errors in markup and would not be rendered on PyPI. line 65: Warning: Title underline too short.
> > > Is this solved in your new PR?
> > 
> > 
> > Hi, I have updated PR #95 to fix the mismatch between the title length and the underlying "~" string. Is that the issue here? However, I haven't yet merged PR #95 due to some other failing tests.
> 
> The issue is coming from the README.rst. I can fix that, in this PR, but I will wait for the other PRs on docs to be merged, then will the full check

I have fixed the issue with line 65 of the README.rst in my recent PR #95. If you now updated this to the latest development branch, you should have no further issues.

**Comment by mohammadamint** [comment]
@FLomb this PR is finalized from my side and believe is ready to be merged

**Review by Bachibouzouk — CHANGES_REQUESTED** [review]
Be careful, the listed commit to be merged have apparently already been merged in PR #95, except they bear different commit numbers. I am not exactly sure how this did happen but 4 of the 6 commits are already into `development` and should not been merged again under other commit numbers. I tried locally to rebase `test-pypy-action` onto `development` and it is done frictionless, only the two commits remain on top of `development`. I can force push this branch if you wish

**Comment by mohammadamint** [comment]
> Be careful, the listed commit to be merged have apparently already been merged in PR #95, except they bear different commit numbers. I am not exactly sure how this did happen but 4 of the 6 commits are already into `development` and should not been merged again under other commit numbers. I tried locally to rebase `test-pypy-action` onto `development` and it is done frictionless, only the two commits remain on top of `development`. I can force push this branch if you wish

Yes please.
I think I am not doing the rebase properly, as the same happened last time. I would ask you later to help me understand how to do it correctly 😊

**Review by Bachibouzouk — APPROVED** [review]

**Review by FLomb — APPROVED** [review]
All looks good to me

**Pull request merged**
