### PR TITLE
Setting Workflows (issue #71)

### PR DESCRIPTION
**Pull request by mohammadamint**
To create an automatic workflow for publishing the package into TestPyPi and PyPi, github actions can be used.

publish to pypi
-----------------
The action is set up to the **main** branch and triggered in event of a new **release** [(workflow file)](https://github.com/RAMP-project/RAMP/blob/workflows/.github/workflows/python-publish-pypi.yml)

TestPypi
---------
The action is set up in development branch , and triggered in event of a push [(workflow file)](https://github.com/RAMP-project/RAMP/blob/workflows/.github/workflows/python-pypi-test.yml)

### CODE REVIEW

**Review by Bachibouzouk — APPROVED** [review]
I don't have experience in auto publish. But the setting files seem to make sense

**Comment by FLomb** [comment]
As @Bachibouzouk , I have no experience with this particular feature, so I'd be happy to test it empirically. One question I have is if we actually want the testing to only occur in the `development` branch; shouldn't it also happen when pushing to the `main` branch, as a double check?

**Comment by Bachibouzouk** [comment]
> shouldn't it also happen when pushing to the `main` branch, as a double check?

I think this is a valid point, the target branches should be both `development` and `main`

**Comment by mohammadamint** [comment]
Sure!

it makes sense. I will add the release to test also in the main branch.

**Pull request merged**
