### PR TITLE
Release v0.4.2

### PR DESCRIPTION
**Pull request by Bachibouzouk**
Remaining TODO in this PR:

- update changelog
- update AUTHORS
- bump version number
- once it is merged into `main` do not delete the branch but merge it into `development`

### CODE REVIEW

**Comment by mohammadamint** [comment]
> Remaining TODO in this PR:
> 
> * update changelog
> * update AUTHORS
> * bump version number
> * once it is merged into `main` do not delete the branch but merge it into `development`

@ I would add black and maybe isort to the list!

**Comment by Bachibouzouk** [comment]
> @Bachibouzouk I would add black and maybe isort to the list!

Then we should do this in separate PRs and then I will rebase the release branch on the dev branch once this has been merged. Normally the release branch should not have too much "work" done into it, only release related stuff: because for black one could apply black and setup a github action which rejects not black linted code. For that we need to pin a black version in the requirements. I would not consider those "release related" commits.

**Comment by FLomb** [comment]
I think it would be great if we could also quickly address issue #83 as part of the new release since that is blocking several old-school users, while it seems that we have found a relatively easy fix in the related GitHub thread. I can implement myself the proposed fix if needed, but it would make more sense for @Bachibouzouk to set up a PR since he proposed such a fix.

**Comment by Bachibouzouk** [comment]
> I can implement myself the proposed fix if needed, but it would make more sense for @Bachibouzouk to set up a PR since he proposed such a fix.

Gladly, I just cannot promise I'll to do it by tomorrow :) I will do it after the lint PR is accepted so I can work with linted code :)

**Comment by FLomb** [comment]
> > I can implement myself the proposed fix if needed, but it would make more sense for @Bachibouzouk to set up a PR since he proposed such a fix.
> 
> Gladly, I just cannot promise I'll to do it by tomorrow :) I will do it after the lint PR is accepted so I can work with linted code :)

Sure, no hurry! (: Thanks

**Comment by Bachibouzouk** [comment]
> So, I think that what needs to happen here is to update the changelog to call this v0.5.0. Are there any other missing things?

I would rather create a new branch `release/0.5.0` from `development`, close this PR and start a new one :)

What needs to be done is already listed in this PR's description

**Comment by Bachibouzouk** [comment]
Taken cared of in #106

**Pull request closed without merging**
